<?xml version="1.0" encoding="UTF-8"?>
<Project>
    <PropertyGroup>
        <Version>20.0.0</Version>
        <PackageReleaseNotes>
          - Adding .NET 10 target framework.
          - Fixed obsolete warnings on X509Certificate loading for .NET 10.
        </PackageReleaseNotes>
    </PropertyGroup>
</Project>
