<?xml version="1.0" encoding="UTF-8"?>
<Project>
    <PropertyGroup>
        <Version>19.1.2</Version>
        <PackageReleaseNotes>
            - Some null-reference warnings in compilation of some unit tests solved (test lifecycle guarantee field is not null during tests)
        </PackageReleaseNotes>
    </PropertyGroup>
</Project>